##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  ÖÜÁù 7ÔÂ 20 17:13:55 2019
##  Generated by MIG Version 4.1
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       VIRTEX7
##                    FPGA Part:         XC7VX690T-FFG1926
##                    Speedgrade:        -2
##                    Design Entry:      VHDL
##                    Frequency:         800 MHz
##                    Time Period:       1250 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K256M8XX-125
## Data Width: 16
## Time Period: 1250
## Data Mask: 1
##################################################################################################
############## NET - IOSTANDARD ##################
#set_property PACKAGE_PIN BD27 [get_ports {led1}]
#set_property IOSTANDARD LVCMOS18 [get_ports {led1}]
#set_property PACKAGE_PIN BD26 [get_ports {led0}]
#set_property IOSTANDARD LVCMOS18 [get_ports {led0}]
#set_property PACKAGE_PIN J30 [get_ports sys_clk_p]
#set_property IOSTANDARD LVDS [get_ports sys_clk_p]
set_property PACKAGE_PIN AW35 [get_ports sdram_pen]
set_property IOSTANDARD LVCMOS18 [get_ports sdram_pen]
set_property PACKAGE_PIN BB37 [get_ports sdram_pg]
set_property IOSTANDARD LVCMOS18 [get_ports sdram_pg]
